# Generated by Django 4.2.5 on 2023-09-25 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ibdr_applicate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_application', models.IntegerField()),
                ('fio', models.CharField(max_length=2000)),
                ('doljn', models.CharField(max_length=100)),
                ('sudis_mail', models.CharField(max_length=200)),
                ('ip', models.CharField(max_length=300)),
                ('telephone', models.CharField(max_length=30)),
                ('vid_uch', models.CharField(max_length=500)),
                ('vid_zap', models.CharField(max_length=1000)),
                ('mej_reg', models.CharField(max_length=3)),
                ('dt_create', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
